# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico # Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dongkyu Lee
title: Ph.D. Candidate at Korea Advanced Institute of Science and Technology (KAIST)
email: dklee@kaist.ac.kr
# email_title: Email (Email title override)
# phone: +82) 10-7642-9842
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  dklee98
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: moving_kyu9
linkedin_username: dongkyu-danial-lee
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: dongkyu lee

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/dongkyu_profile_zoomzoom.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in the [Department of Electrical Engineering](https://ee.kaist.ac.kr/) at [KAIST](https://kaist.ac.kr/kr/), and a member of the [Urban Robotics Lab](https://urobot.kaist.ac.kr) led by Prof. [Hyun Myung](https://urobot.kaist.ac.kr/url_teams/prof-hyunmyung/).
  My current research interests lie in autonomous navigation for legged robots, focusing on developing motion and path planning, decision-making, and the interplay between SLAM and navigation algorithms for long-term field robotics applications.


# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Ph.D.
        sub_title: Department of Electrical Engineering
        caption: Korea Advanced Institute of Science and Technology (KAIST), South Korea
        quote: Sep. 2023 - present

      - layout: top-middle
        title: M.S.
        sub_title: Robotics Program
        caption: Korea Advanced Institute of Science and Technology (KAIST), South Korea
        quote: Sep. 2021 - Aug. 2023
      
      - layout: top-middle
        title: B.S.
        sub_title: School of Electrical and Computer Engineering
        caption: University of Seoul (UOS), South Korea
        quote: Mar. 2016 - Aug. 2021

  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: |
            <img src="images/kaist.png" width="240px" margin-bottom="300%"> <br>
        description: | # this will include new lines to allow paragraphs
          **Research Intern**

          *Urban Robotics Lab, KAIST*, South Korea

          Feb.2021 - Aug.2021
  
      - layout: left
        title: |
            <img src="images/etri.png" width="240px" margin-bottom="300%"> <br>
        description: | # this will include new lines to allow paragraphs
          **Research Intern**

          *Artificial Intelligence Research Team, Electronics and Telecommunications Research Institute (ETRI)*, South Korea

          Jan.2021 - Feb.2021

      - layout: left
        title: | # software maestro
            <img src="images/swm.png" width="240px" margin-bottom="300%"> <br>
        description: | # this will include new lines to allow paragraphs
          **Research Intern**

          *Software Maestro 11th, Ministry of Science and ICT (MSIT)*, South Korea

          Jun.2020 - Dec.2020

  - title: Research Highlights
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
            <img src="images/trg.png" width="240px" margin-bottom="300%"> <br>
        description: | # this will include new lines to allow paragraphs
          ***TRG-Planner: Traversal Risk Graph-Based Path Planning in Unstructured Environments for Safe and Efficient Navigation***

          **Dongkyu Lee**, I Made Aswin Nahrendra, Minho Oh, Byeongho Yu, and Hyun Myung

          IEEE Robotics and Automation Letters **(RA-L), 2025**

          <a href="https://arxiv.org/abs/2501.01806">Paper</a>  <a href="https://trg-planner.github.io/">Project</a>
  
  - title: Selected Publications
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
            <img src="images/dreamflex.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***DreamFLEX: Learning Fault-Aware Quadrupedal Locomotion Controller for Anomaly Situation in Rough Terrains***

                    Seunghyun Lee, I Made Aswin Nahrendra, **Dongkyu Lee**, Byeongho Yu, Minho Oh, and Hyun Myung

                    IEEE International Conference on Robotics and Automation **(ICRA), 2025**

                    <a href="https://dreamflex.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/dreamwaqpp.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***DreamWaQ++: Obstacle-aware Quadrupedal Locomotion with Resilient Multi-modal Reinforcement Learning***

                    I Made Aswin Nahrendra, Byeongho Yu, Minho Oh, **Dongkyu Lee**, Seunghyun Lee, Hyeonwoo Lee, Hyungtae Lim, and Hyun Myung

                    **under review**

                    <a href="https://arxiv.org/pdf/2409.19709">Paper</a>  <a href="https://dreamwaqpp.github.io">Project</a>
      
      - layout: left
        title: |
            <img src="images/trip.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***TRIP: Terrain Traversability Mapping With Risk-Aware Prediction for Enhanced Online Quadrupedal Robot Navigation***

                    Minho Oh, Byeongho Yu, I Nahrendra, Seoyeon Jang, Hyeonwoo Lee, **Dongkyu Lee**, Seungjae Lee, Yeeun Kim, Marsim Kevin Christiansen, Hyungtae Lim, Hyun Myung

                    **under review**

                    <a href="https://arxiv.org/abs/2411.17134">Paper</a>
                  
  - title: Awards
    layout: list
    content: 

      - layout: left
        title: |
            <img src="images/dreamstep.jpg" width="240" margin-bottom="300%"> <br>
        sub_title: Winner
        caption: Team DreamStep of KAIST
        link: https://quadruped-robot-challenges.notion.site/ICRA-2023-Quadruped-Robot-Challenges
        description: | 
                      ***Autonomous Quadrupedal Robot Challenge in ICRA 2023, London***

                      Role: Safe path planning using TRG-planner

      - layout: left
        title: |
            <img src="images/kroc_2024.png" width="240" margin-bottom="300%"> <br>
        sub_title: Best Work Award
        # caption: Team QAIST++ of KAIST
        link: https://urobot.kaist.ac.kr/announcement/?uid=517&mod=document&pageid=1
        description: |
                    ***KROC 2024 RED Show***

                    Development of various gait pattern locomotion for quadruped robots using deep reinforcement learning
  
  - title: Other Publications
    layout: text
    content: | # this will include new lines to allow paragraphs

      - <a>*B-TMS:\ Bayesian Traversable Terrain Modeling and Segmentation Across 3D LiDAR Scans and Maps for Enhanced Off-Road Navigation*</a>
      
        Minho Oh, Gunhee Shin, Seoyeon Jang, Seungjae Lee, **Dongkyu Lee**, Wonho Song, Byeongho Yu, Hyungtae Lim, Jaeyoung Lee, Hyun Myung
         
        IEEE Intelligent Vehicles Symposium **(IV), 2024**


      - <a>*M-BRIC:\ design of mass-driven bi-rotor with RL-based intelligent controller*</a>
      
      - <a>*FARO-Tracker:\ Fast and robust target tracking system for UAVs in urban environment*</a>

      - <a>*Ceo-mlcpp:\ Control-efficient and obstacle-aware multi-layer coverage path planner for 3d reconstruction with uavs*</a>

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
